server:
 port: 8888

cors:
 originPatterns: http://localhost:4200,http://localhost:8888
 
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sentinela_db?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: admin
    password: 1234

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    open-in-view: false